SELECT * FROM PARTY;

        --QUESTION1 (ALTER TABLE)
        ALTER TABLE PARTYADDRESS
        ADD  PRIMARYADDRESS VARCHAR(50);
        
        --QUESTION2  (INSERT COMMAND)
        INSERT INTO PARTY (PARTYSEQ, FIRSTNAME, LASTNAME1) VALUES(22556699, 'BHAVESH','KHANDAR');
        
        
        --QUESTION 3 (SELECT QUERIES WITH SUBQUESTIONS)
        -- A.
      SELECT * FROM PARTY;
      
        -- B.
        SELECT PARTYSEQ, PARTYID, FIRSTNAME,LASTNAME1 FROM PARTY;
        
        --C.I 
        SELECT * FROM PARTY WHERE PARTYID = '00004661';
        
        --C.II
        SELECT * FROM PARTY WHERE PARTYTYPECD ='INDIVIDUAL' OR PARTYTYPECD='ORGANIZATION';
        
        --C.III
        SELECT * FROM PARTY WHERE FIRSTNAME = 'KELLY';
        
        --C.IV
        SELECT * FROM PARTY WHERE OCCUPATIONCLASS = 'Programmer';
        
        --C.V
        SELECT * FROM PARTYADDRESS WHERE PARTYSEQ = 5904;
        
        --C.VI
        SELECT * FROM PARTYADDRESS WHERE CITYCD = 'wew' AND STATECD = 'PENANG';
        
        --C.VII
        SELECT * FROM PARTYCONTACT WHERE PARTYSEQ = 5904;
        
        --C.VIII
        SELECT PARTYSEQ FROM PARTYCONTACT WHERE CONTACTNUM 1111111111;
        
        --C.IX
        SELECT ADDRESSTYPECD, PARTYSEQ 
        FROM PARTYADDRESS
        WHERE CITYCD IN('wew');
        
        --C.X
        SELECT * FROM PARTYCONTACT
        WHERE PARTYSEQ BETWEEN 5850 AND 5900;
        
        --C.XI
        SELECT FIRSTNAME, LASTNAME
        FROM QUOTATIONPARTY
        WHERE ROLECD != 'PROPOSER' AND DOB < '01-01-1999';
        
        --C.XII
        SELECT FIRSTNAME, LASTNAME 
        FROM QUOTATIONPARTY
        WHERE OCCUPATIONCD  = 'Programmer' AND ROLECD = 'PROPOSER' ;
        
        --C.XIII
        SELECT FIRSTNAME, LASTNAME, AGE
        FROM QUOTATIONPARTY
        WHERE GENDERCD = 'FEMALE'
        AND AGE > 30
        ORDER BY AGE DESC;

        --C.XIV
        SELECT AVG(AGE)
        FROM  QUOTATIONPARTY
        WHERE ROLECD = 'PROPOSER';
        
        --C.XV
        SELECT MAX(AGE),MIN(AGE)
        FROM QUOTATIONPARTY
        WHERE ROLECD = 'PROPOSER';
        
        -- QUESTION 4. I
        SELECT P.FIRSTNAME, A.ADDRESSTYPECD, C.CONTACTNUM
        FROM PARTY P
        JOIN PARTYCONTACT C ON P.PARTYSEQ = C.PARTYSEQ
        JOIN PARTYADDRESS A ON P.PARTYSEQ = A.PARTYSEQ
        WHERE C.CONTACTNUM = '9878987888';
        
        --4. II
        SELECT P.FIRSTNAME, P.LASTNAME1, P.BIRTHDT, P.PARTYSTATUS, C.CONTACTNUM, A.ADDRESSTYPECD
        FROM PARTY P
        JOIN PARTYCONTACT C ON P.PARTYSEQ = C.PARTYSEQ
        JOIN PARTYADDRESS A ON P.PARTYSEQ = A.PARTYSEQ
        WHERE P.FIRSTNAME = 'AMAR';
        
        --4. III
      SELECT P.PARTYSEQ, P.FIRSTNAME, 
        CASE 
           WHEN E.EMAILADDRESS IS NOT NULL THEN E.EMAILADDRESS
           ELSE P.FIRSTNAME
        END AS EMAIL
        FROM PARTY P
        LEFT JOIN PARTYEMAIL E ON P.PARTYSEQ = E.PARTYSEQ;


        --4. IV
        
      SELECT P.PARTYSEQ, P.FIRSTNAME
      FROM PARTY P
      INNER JOIN PARTYEMAIL E ON P.PARTYSEQ = E.PARTYSEQ;
      
      
      -- QUESTION 5. I
      SELECT ADDRESSTYPECD
      FROM PARTYADDRESS
      WHERE PARTYSEQ IN  (SELECT PARTYSEQ FROM PARTY WHERE FIRSTNAME = 'MAHESH');
      
      -- QUESTION 5.II
      SELECT LABELVALUE FROM LABELVALUE_M
      WHERE LABELSEQ IN
      (SELECT LABELSEQ FROM LABEL_M WHERE LABELKEY =
      (SELECT PROPERTYVALUE FROM Uimetadataproperty_M 
      WHERE METADATACD = 'PartyDO.partyTypeCd' AND PROPERTYCD LIKE 'LABELKEY'));
      
        -- 5. II REVERSE 
     SELECT METADATACD FROM UIMETADATAPROPERTY_M 
     WHERE PROPERTYVALUE LIKE 
     (SELECT LABELKEY FROM LABEL_M WHERE LABELSEQ = 
     (SELECT LABELSEQ FROM LABELVALUE_M WHERE LABELVALUE = 'Owner type'));
     
      -- QUESTION 5.III
      
      SELECT DISTINCT(LOOKUPDATAVALUEKEY) FROM LOOKUPDATA_M
      WHERE LOOKUPKEY IN
      (SELECT LOOKUPKEY FROM LOOKUP_M WHERE LOOKUPKEY IN 
      (SELECT PROPERTYVALUE FROM UIMETADATAPROPERTY_M WHERE METADATACD ='PartyDO.genderCd' AND PROPERTYCD = 'LOOKUPCD'));
      
      -- QUESTION 5. III REVERSE
      
      SELECT DISTINCT(METADATACD) FROM Uimetadataproperty_M
      WHERE Propertyvalue IN
      (SELECT LOOKUPKEY FROM LOOKUP_M WHERE LOOKUPKEY IN
      (SELECT LOOKUPKEY FROM LOOKUPDATA_M WHERE Lookupdatavaluekey = 'Male'));
      
      
      -- QUESTION 6. I
      CREATE VIEW DETAIL_VIEW
      AS SELECT P.FIRSTNAME, A.ADDRESSTYPECD, C.CONTACTNUM
      FROM PARTY P
      JOIN PARTYADDRESS A ON P.PARTYSEQ = A.PARTYSEQ
      JOIN PARTYCONTACT C ON P.PARTYSEQ = C.PARTYSEQ;
      
      SELECT * FROM DETAIL_VIEW;
      
      
      -- QUESTION 6. II
      CREATE TABLE NEWTABLE (PARTYSEQ NUMBER,  NAME VARCHAR(50), CONTACT VARCHAR(10));
      
     

      